### ISSUE TITLE
Replace mimemagic

### ISSUE THREAD

**Issue by bmulholland** [aspose-words-cloud/aspose-words-cloud-ruby#1]
Are there plans to drop mimemagic, given the licensing issue and ensuing added external dependency?

See e.g. https://github.com/rails/rails/issues/41750

**Comment by bmulholland** [comment]
There's a drop-in replacement here: https://github.com/rails/marcel/blob/main/lib/marcel/magic.rb#L85

**Comment by YaroslawEkimov** [comment]
Hi, we published new version with updated dependencies https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/blob/master/aspose_words_cloud.gemspec
