### ISSUE TITLE
Upgrade ruby requirement

### ISSUE THREAD

**Issue by bmulholland** [aspose-words-cloud/aspose-words-cloud-ruby#3]
Ruby 2.3 was EOL'd in 2019: https://endoflife.software/programming-languages/server-side-scripting/ruby - and this gem requires only ruby 2.3, no newer versions allowed.

**Comment by YaroslawEkimov** [comment]
fixed https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/blob/de5ad961b4a8efb2d5751109466cdb7505fbdd4e/aspose_words_cloud.gemspec#L22
