### ISSUE TITLE
URI.escape is obsolete

### ISSUE THREAD

**Issue by bmulholland** [aspose-words-cloud/aspose-words-cloud-ruby#5]
I'm getting this warning from using the gem: "bundler/gems/aspose-words-cloud-ruby-c8afc168b69d/lib/aspose_words_cloud/configuration.rb:122: warning: URI.escape is obsolete"

**Comment by YaroslawEkimov** [comment]
it was fixed here https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/blob/de5ad961b4a8efb2d5751109466cdb7505fbdd4e/lib/aspose_words_cloud/configuration.rb#L122
