### ISSUE TITLE
Correctly upload Tempfiles

### ISSUE THREAD

**Issue by bmulholland** [aspose-words-cloud/aspose-words-cloud-ruby#6]
When trying to upload a Tempfile, the API call succeeds (and I am charged for it!) but no file is uploaded!

That's because this line only deals with File objects - and for some reason that I do not agree with, in Ruby, an instance of a Tempfile is not a File. It is instead a delegate class of file.

https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/blob/8bcbb18654f1a0225bed88403bf46eb4bfc7f0d1/lib/aspose_words_cloud/api_client.rb#L347

The line should be changed to `when ::File, ::Tempfile`

**Comment by bmulholland** [comment]
Working fix on my fork: https://github.com/recitalsoftware/aspose-words-cloud-ruby/commit/920fa1b8f8c2945390eb82624664d421d83b6c9c#diff-dcda03a6b21a7bbd2d33fc888c06127f80353b99b7e053f8d16c3c2411b5655e

**Comment by YaroslawEkimov** [comment]
fixed https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/blob/de5ad961b4a8efb2d5751109466cdb7505fbdd4e/lib/aspose_words_cloud/api_client.rb#L393
