### ISSUE TITLE
`AsposeWordsCloud::WordsApi#compare_document_online` returns a `TempFile` that not usable.

### ISSUE THREAD

**Issue by dimerman** [aspose-words-cloud/aspose-words-cloud-ruby#7]
sample code
```ruby
response = AsposeWordsCloud::WordsApi.new.compare_document_online(
  AsposeWordsCloud::CompareDocumentOnlineRequest.new(
    base_file,
    compare_options(
      revision_author: revision_author,
      revision_time: revision_time,
    ),
    revised_file,
  ),
)

temp_file = response.document
```

**The `temp_file` should have been rewound.** 

Without documentation on the state of the temporary file returned, a naive use of this API would assume the file is ready to be consumed, causing cascading errors difficult to trace.
If the tempfile returned is not rewound, it might be interpreted as an empty file (which in some scenarios is a legitimate response). This is in contradiction with earlier API behaviour.

**Comment by YaroslawEkimov** [comment]
hi, file rewind was added, and will be released with next release. In case you use version from github you can already get this fix from https://github.com/aspose-words-cloud/aspose-words-cloud-ruby/commit/340d0d2faab5c2ae045ae59965cf1a30a9edd2d7 commit.
Thanks for you interest in our product.
