### ISSUE TITLE
Aspose uses deprecated class from Faraday@1.8.0

### ISSUE THREAD

**Issue by dimerman** [aspose-words-cloud/aspose-words-cloud-ruby#9]
the gem relies on Faraday's class `Faraday::UploadIO` which is [deprecated](https://github.com/lostisland/faraday/blob/d0efa092829362f95d4b71d3bcd3c52189b74277/lib/faraday/file_part.rb#L59).
upgrading faraday above `1.8.0` breaks aspose.

**Comment by YaroslawEkimov** [comment]
Hi, issue has been fixed in latest release
